Feature diff
bornobob/Notepad-- pull request #42
Opened 2020-12-04 18:10 UTC by huynguy97

Works like a train. Tested big (4k lines) files as well. Also has input validation for security reasons.

2020-12-04 18:57 UTC, jwijenbergh commented
We now really need the totalTabs variable to always increase, see `3f6e157`

2020-12-04 19:49 UTC, huynguy97 commented
Currently theres a bug when you add tabs, remove tabs and then try to diff. This is because our tab implementation.

2020-12-04 22:36 UTC, huynguy97 commented
Fixed it, code is still a bit dirty but will clean it up.

2020-12-07 14:28 UTC, bornobob requested changes
Some quite small changes

2020-12-07 14:28 UTC, bornobob commented on editor/app.py
> +from flask import Flask, render_template, request, redirect, jsonify
remove jsonify

2020-12-07 14:28 UTC, bornobob commented on editor/app.py
> +import json
remove json

2020-12-07 14:28 UTC, bornobob commented on editor/app.py
remove extra new line

2020-12-07 14:28 UTC, bornobob commented on editor/diff.py
> +
one too many newline

2020-12-07 14:31 UTC, huynguy97 commented on editor/app.py
> +from flask import Flask, render_template, request, redirect, jsonify
removed

2020-12-07 14:31 UTC, huynguy97 commented on editor/app.py
> +import json
removed

2020-12-07 14:31 UTC, huynguy97 commented on editor/app.py
removed

2020-12-07 14:34 UTC, bornobob approved these changes
Looks good!

2020-12-07 14:34 UTC, Justin-Reniers commented on editor/templates/diff/index.html
> +
Remove newlines

2020-12-07 14:34 UTC, Justin-Reniers commented on aop/extensions/diff.py
> +            return html, 200
Maybe do this with `jsonify`, so you'd get something more akin to `return jsonify(success=False, message='msg: {}'.format(message))`

2020-12-07 14:42 UTC, Justin-Reniers approved these changes
Looks good!

2020-12-07 14:43 UTC, bornobob approved these changes
Still looks good

2020-12-07 14:44 UTC, merged

2020-12-07 14:44 UTC, jwijenbergh approved these changes
Looks good everybody!